# Generated by Django 3.1.6 on 2021-03-08 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donators',
            fields=[
                ('don_id', models.AutoField(primary_key=True, serialize=False)),
                ('don_user_name', models.CharField(max_length=30)),
                ('don_book_name', models.CharField(max_length=300)),
                ('don_book_cat', models.CharField(max_length=30)),
                ('don_ts', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
