# Generated by Django 3.1.6 on 2021-03-09 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_user', models.CharField(max_length=30)),
                ('con_email', models.CharField(max_length=90)),
                ('con_phone', models.CharField(max_length=20)),
                ('con_location', models.CharField(max_length=200)),
                ('con_desc', models.TextField()),
                ('con_ts', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
